/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DisputeDAO {
  export type ArbitratorStruct = {
    stake: BigNumberish;
    disputesResolved: BigNumberish;
    correctVotes: BigNumberish;
    totalVotes: BigNumberish;
    totalEarned: BigNumberish;
    isActive: boolean;
    registeredAt: BigNumberish;
  };

  export type ArbitratorStructOutput = [
    stake: bigint,
    disputesResolved: bigint,
    correctVotes: bigint,
    totalVotes: bigint,
    totalEarned: bigint,
    isActive: boolean,
    registeredAt: bigint
  ] & {
    stake: bigint;
    disputesResolved: bigint;
    correctVotes: bigint;
    totalVotes: bigint;
    totalEarned: bigint;
    isActive: boolean;
    registeredAt: bigint;
  };

  export type DisputeStruct = {
    escrowOrderId: BytesLike;
    buyer: AddressLike;
    seller: AddressLike;
    amount: BigNumberish;
    tier: BigNumberish;
    status: BigNumberish;
    reason: string;
    buyerEvidence: BytesLike;
    sellerEvidence: BytesLike;
    selectedArbitrators: [AddressLike, AddressLike, AddressLike];
    votesForBuyer: BigNumberish;
    votesForSeller: BigNumberish;
    finalDecision: boolean;
    createdAt: BigNumberish;
    votingDeadline: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type DisputeStructOutput = [
    escrowOrderId: string,
    buyer: string,
    seller: string,
    amount: bigint,
    tier: bigint,
    status: bigint,
    reason: string,
    buyerEvidence: string,
    sellerEvidence: string,
    selectedArbitrators: [string, string, string],
    votesForBuyer: bigint,
    votesForSeller: bigint,
    finalDecision: boolean,
    createdAt: bigint,
    votingDeadline: bigint,
    resolvedAt: bigint
  ] & {
    escrowOrderId: string;
    buyer: string;
    seller: string;
    amount: bigint;
    tier: bigint;
    status: bigint;
    reason: string;
    buyerEvidence: string;
    sellerEvidence: string;
    selectedArbitrators: [string, string, string];
    votesForBuyer: bigint;
    votesForSeller: bigint;
    finalDecision: boolean;
    createdAt: bigint;
    votingDeadline: bigint;
    resolvedAt: bigint;
  };

  export type VoteStruct = {
    hasVoted: boolean;
    favorBuyer: boolean;
    reasoning: string;
    votedAt: BigNumberish;
  };

  export type VoteStructOutput = [
    hasVoted: boolean,
    favorBuyer: boolean,
    reasoning: string,
    votedAt: bigint
  ] & {
    hasVoted: boolean;
    favorBuyer: boolean;
    reasoning: string;
    votedAt: bigint;
  };
}

export interface DisputeDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addArbitratorStake"
      | "adminResolve"
      | "arbitratorList"
      | "arbitratorRewardBps"
      | "arbitrators"
      | "createDispute"
      | "disputeCount"
      | "disputeVotes"
      | "disputes"
      | "escrowContract"
      | "forceResolve"
      | "getActiveArbitratorCount"
      | "getArbitrator"
      | "getArbitratorAccuracy"
      | "getDispute"
      | "getVote"
      | "maxDisputeRateBps"
      | "minArbitratorStake"
      | "minArbitratorTrades"
      | "owner"
      | "registerArbitrator"
      | "renounceOwnership"
      | "setEscrowContract"
      | "setMinArbitratorStake"
      | "setVotingPeriod"
      | "startVoting"
      | "submitEvidence"
      | "transferOwnership"
      | "usdc"
      | "voteOnDispute"
      | "votesRequired"
      | "votingPeriod"
      | "withdrawArbitratorStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitratorPenalized"
      | "ArbitratorRegistered"
      | "ArbitratorRemoved"
      | "ArbitratorRewarded"
      | "ArbitratorsSelected"
      | "DisputeCreated"
      | "DisputeEscalated"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addArbitratorStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminResolve",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitratorList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitratorRewardBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeVotes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceResolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveArbitratorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getArbitrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArbitratorAccuracy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDisputeRateBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minArbitratorStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minArbitratorTrades",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerArbitrator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinArbitratorStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startVoting",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteOnDispute",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "votesRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawArbitratorStake",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addArbitratorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitratorList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitratorRewardBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitrators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveArbitratorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArbitratorAccuracy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxDisputeRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minArbitratorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minArbitratorTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinArbitratorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votesRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawArbitratorStake",
    data: BytesLike
  ): Result;
}

export namespace ArbitratorPenalizedEvent {
  export type InputTuple = [
    arbitrator: AddressLike,
    accuracyDropBps: BigNumberish
  ];
  export type OutputTuple = [arbitrator: string, accuracyDropBps: bigint];
  export interface OutputObject {
    arbitrator: string;
    accuracyDropBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArbitratorRegisteredEvent {
  export type InputTuple = [arbitrator: AddressLike, stake: BigNumberish];
  export type OutputTuple = [arbitrator: string, stake: bigint];
  export interface OutputObject {
    arbitrator: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArbitratorRemovedEvent {
  export type InputTuple = [arbitrator: AddressLike];
  export type OutputTuple = [arbitrator: string];
  export interface OutputObject {
    arbitrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArbitratorRewardedEvent {
  export type InputTuple = [arbitrator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [arbitrator: string, amount: bigint];
  export interface OutputObject {
    arbitrator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArbitratorsSelectedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    arbitrators: [AddressLike, AddressLike, AddressLike]
  ];
  export type OutputTuple = [
    disputeId: bigint,
    arbitrators: [string, string, string]
  ];
  export interface OutputObject {
    disputeId: bigint;
    arbitrators: [string, string, string];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    escrowOrderId: BytesLike,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    escrowOrderId: string,
    tier: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    escrowOrderId: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeEscalatedEvent {
  export type InputTuple = [disputeId: BigNumberish, newTier: BigNumberish];
  export type OutputTuple = [disputeId: bigint, newTier: bigint];
  export interface OutputObject {
    disputeId: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [disputeId: BigNumberish, buyerWins: boolean];
  export type OutputTuple = [disputeId: bigint, buyerWins: boolean];
  export interface OutputObject {
    disputeId: bigint;
    buyerWins: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    arbitrator: AddressLike,
    favorBuyer: boolean
  ];
  export type OutputTuple = [
    disputeId: bigint,
    arbitrator: string,
    favorBuyer: boolean
  ];
  export interface OutputObject {
    disputeId: bigint;
    arbitrator: string;
    favorBuyer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisputeDAO extends BaseContract {
  connect(runner?: ContractRunner | null): DisputeDAO;
  waitForDeployment(): Promise<this>;

  interface: DisputeDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addArbitratorStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminResolve: TypedContractMethod<
    [disputeId: BigNumberish, favorBuyer: boolean],
    [void],
    "nonpayable"
  >;

  arbitratorList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  arbitratorRewardBps: TypedContractMethod<[], [bigint], "view">;

  arbitrators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stake: bigint;
        disputesResolved: bigint;
        correctVotes: bigint;
        totalVotes: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  createDispute: TypedContractMethod<
    [
      escrowOrderId: BytesLike,
      buyer: AddressLike,
      seller: AddressLike,
      amount: BigNumberish,
      reason: string,
      tier: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  disputeCount: TypedContractMethod<[], [bigint], "view">;

  disputeVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, string, bigint] & {
        hasVoted: boolean;
        favorBuyer: boolean;
        reasoning: string;
        votedAt: bigint;
      }
    ],
    "view"
  >;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        escrowOrderId: string;
        buyer: string;
        seller: string;
        amount: bigint;
        tier: bigint;
        status: bigint;
        reason: string;
        buyerEvidence: string;
        sellerEvidence: string;
        votesForBuyer: bigint;
        votesForSeller: bigint;
        finalDecision: boolean;
        createdAt: bigint;
        votingDeadline: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  escrowContract: TypedContractMethod<[], [string], "view">;

  forceResolve: TypedContractMethod<
    [disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveArbitratorCount: TypedContractMethod<[], [bigint], "view">;

  getArbitrator: TypedContractMethod<
    [arb: AddressLike],
    [DisputeDAO.ArbitratorStructOutput],
    "view"
  >;

  getArbitratorAccuracy: TypedContractMethod<
    [arb: AddressLike],
    [bigint],
    "view"
  >;

  getDispute: TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeDAO.DisputeStructOutput],
    "view"
  >;

  getVote: TypedContractMethod<
    [disputeId: BigNumberish, arb: AddressLike],
    [DisputeDAO.VoteStructOutput],
    "view"
  >;

  maxDisputeRateBps: TypedContractMethod<[], [bigint], "view">;

  minArbitratorStake: TypedContractMethod<[], [bigint], "view">;

  minArbitratorTrades: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerArbitrator: TypedContractMethod<
    [stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEscrowContract: TypedContractMethod<
    [_escrow: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinArbitratorStake: TypedContractMethod<
    [_stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVotingPeriod: TypedContractMethod<
    [_period: BigNumberish],
    [void],
    "nonpayable"
  >;

  startVoting: TypedContractMethod<
    [disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [disputeId: BigNumberish, evidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  voteOnDispute: TypedContractMethod<
    [disputeId: BigNumberish, favorBuyer: boolean, reasoning: string],
    [void],
    "nonpayable"
  >;

  votesRequired: TypedContractMethod<[], [bigint], "view">;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  withdrawArbitratorStake: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addArbitratorStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminResolve"
  ): TypedContractMethod<
    [disputeId: BigNumberish, favorBuyer: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "arbitratorList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "arbitratorRewardBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbitrators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stake: bigint;
        disputesResolved: bigint;
        correctVotes: bigint;
        totalVotes: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDispute"
  ): TypedContractMethod<
    [
      escrowOrderId: BytesLike,
      buyer: AddressLike,
      seller: AddressLike,
      amount: BigNumberish,
      reason: string,
      tier: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, string, bigint] & {
        hasVoted: boolean;
        favorBuyer: boolean;
        reasoning: string;
        votedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        escrowOrderId: string;
        buyer: string;
        seller: string;
        amount: bigint;
        tier: bigint;
        status: bigint;
        reason: string;
        buyerEvidence: string;
        sellerEvidence: string;
        votesForBuyer: bigint;
        votesForSeller: bigint;
        finalDecision: boolean;
        createdAt: bigint;
        votingDeadline: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forceResolve"
  ): TypedContractMethod<[disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveArbitratorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getArbitrator"
  ): TypedContractMethod<
    [arb: AddressLike],
    [DisputeDAO.ArbitratorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArbitratorAccuracy"
  ): TypedContractMethod<[arb: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeDAO.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [disputeId: BigNumberish, arb: AddressLike],
    [DisputeDAO.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxDisputeRateBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minArbitratorStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minArbitratorTrades"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerArbitrator"
  ): TypedContractMethod<[stakeAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrowContract"
  ): TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinArbitratorStake"
  ): TypedContractMethod<[_stake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVotingPeriod"
  ): TypedContractMethod<[_period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startVoting"
  ): TypedContractMethod<[disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [disputeId: BigNumberish, evidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voteOnDispute"
  ): TypedContractMethod<
    [disputeId: BigNumberish, favorBuyer: boolean, reasoning: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votesRequired"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawArbitratorStake"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ArbitratorPenalized"
  ): TypedContractEvent<
    ArbitratorPenalizedEvent.InputTuple,
    ArbitratorPenalizedEvent.OutputTuple,
    ArbitratorPenalizedEvent.OutputObject
  >;
  getEvent(
    key: "ArbitratorRegistered"
  ): TypedContractEvent<
    ArbitratorRegisteredEvent.InputTuple,
    ArbitratorRegisteredEvent.OutputTuple,
    ArbitratorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ArbitratorRemoved"
  ): TypedContractEvent<
    ArbitratorRemovedEvent.InputTuple,
    ArbitratorRemovedEvent.OutputTuple,
    ArbitratorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ArbitratorRewarded"
  ): TypedContractEvent<
    ArbitratorRewardedEvent.InputTuple,
    ArbitratorRewardedEvent.OutputTuple,
    ArbitratorRewardedEvent.OutputObject
  >;
  getEvent(
    key: "ArbitratorsSelected"
  ): TypedContractEvent<
    ArbitratorsSelectedEvent.InputTuple,
    ArbitratorsSelectedEvent.OutputTuple,
    ArbitratorsSelectedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeEscalated"
  ): TypedContractEvent<
    DisputeEscalatedEvent.InputTuple,
    DisputeEscalatedEvent.OutputTuple,
    DisputeEscalatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ArbitratorPenalized(address,uint256)": TypedContractEvent<
      ArbitratorPenalizedEvent.InputTuple,
      ArbitratorPenalizedEvent.OutputTuple,
      ArbitratorPenalizedEvent.OutputObject
    >;
    ArbitratorPenalized: TypedContractEvent<
      ArbitratorPenalizedEvent.InputTuple,
      ArbitratorPenalizedEvent.OutputTuple,
      ArbitratorPenalizedEvent.OutputObject
    >;

    "ArbitratorRegistered(address,uint256)": TypedContractEvent<
      ArbitratorRegisteredEvent.InputTuple,
      ArbitratorRegisteredEvent.OutputTuple,
      ArbitratorRegisteredEvent.OutputObject
    >;
    ArbitratorRegistered: TypedContractEvent<
      ArbitratorRegisteredEvent.InputTuple,
      ArbitratorRegisteredEvent.OutputTuple,
      ArbitratorRegisteredEvent.OutputObject
    >;

    "ArbitratorRemoved(address)": TypedContractEvent<
      ArbitratorRemovedEvent.InputTuple,
      ArbitratorRemovedEvent.OutputTuple,
      ArbitratorRemovedEvent.OutputObject
    >;
    ArbitratorRemoved: TypedContractEvent<
      ArbitratorRemovedEvent.InputTuple,
      ArbitratorRemovedEvent.OutputTuple,
      ArbitratorRemovedEvent.OutputObject
    >;

    "ArbitratorRewarded(address,uint256)": TypedContractEvent<
      ArbitratorRewardedEvent.InputTuple,
      ArbitratorRewardedEvent.OutputTuple,
      ArbitratorRewardedEvent.OutputObject
    >;
    ArbitratorRewarded: TypedContractEvent<
      ArbitratorRewardedEvent.InputTuple,
      ArbitratorRewardedEvent.OutputTuple,
      ArbitratorRewardedEvent.OutputObject
    >;

    "ArbitratorsSelected(uint256,address[3])": TypedContractEvent<
      ArbitratorsSelectedEvent.InputTuple,
      ArbitratorsSelectedEvent.OutputTuple,
      ArbitratorsSelectedEvent.OutputObject
    >;
    ArbitratorsSelected: TypedContractEvent<
      ArbitratorsSelectedEvent.InputTuple,
      ArbitratorsSelectedEvent.OutputTuple,
      ArbitratorsSelectedEvent.OutputObject
    >;

    "DisputeCreated(uint256,bytes32,uint8)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeEscalated(uint256,uint8)": TypedContractEvent<
      DisputeEscalatedEvent.InputTuple,
      DisputeEscalatedEvent.OutputTuple,
      DisputeEscalatedEvent.OutputObject
    >;
    DisputeEscalated: TypedContractEvent<
      DisputeEscalatedEvent.InputTuple,
      DisputeEscalatedEvent.OutputTuple,
      DisputeEscalatedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
