/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace P2PEscrowV2 {
  export type EscrowStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    fee: BigNumberish;
    stakeAmount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    disputedAt: BigNumberish;
    disputeReason: string;
    paymentProofHash: BytesLike;
  };

  export type EscrowStructOutput = [
    sender: string,
    recipient: string,
    amount: bigint,
    fee: bigint,
    stakeAmount: bigint,
    status: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    disputedAt: bigint,
    disputeReason: string,
    paymentProofHash: string
  ] & {
    sender: string;
    recipient: string;
    amount: bigint;
    fee: bigint;
    stakeAmount: bigint;
    status: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    disputedAt: bigint;
    disputeReason: string;
    paymentProofHash: string;
  };

  export type StakeProfileStruct = {
    baseStake: BigNumberish;
    lockedStake: BigNumberish;
    tradingLimit: BigNumberish;
    lastTradeTime: BigNumberish;
    completedTrades: BigNumberish;
    disputesLost: BigNumberish;
    isLP: boolean;
  };

  export type StakeProfileStructOutput = [
    baseStake: bigint,
    lockedStake: bigint,
    tradingLimit: bigint,
    lastTradeTime: bigint,
    completedTrades: bigint,
    disputesLost: bigint,
    isLP: boolean
  ] & {
    baseStake: bigint;
    lockedStake: bigint;
    tradingLimit: bigint;
    lastTradeTime: bigint;
    completedTrades: bigint;
    disputesLost: bigint;
    isLP: boolean;
  };
}

export interface P2PEscrowV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "SLASH_DISPUTE_LOST"
      | "SLASH_FAKE_PROOF"
      | "SLASH_LATE_RELEASE"
      | "SLASH_ORDER_TIMEOUT"
      | "SLASH_PAYMENT_REVERSAL"
      | "arbitrator"
      | "baseStakeBps"
      | "calculateRequiredStake"
      | "createEscrow"
      | "dailyVolume"
      | "depositStake"
      | "disputeDAO"
      | "disputeTimeout"
      | "escrows"
      | "getAvailableStake"
      | "getEscrow"
      | "getStakeProfile"
      | "lastVolumeReset"
      | "maxDailyVolume"
      | "owner"
      | "pause"
      | "paused"
      | "paymentMethodRisk"
      | "platformFeeBps"
      | "raiseDispute"
      | "rateLimitSeconds"
      | "refundEscrow"
      | "releaseEscrow"
      | "renounceOwnership"
      | "resolveDispute"
      | "riskMultipliers"
      | "setArbitrator"
      | "setBaseStake"
      | "setDisputeDAO"
      | "setMaxDailyVolume"
      | "setPlatformFee"
      | "stakes"
      | "submitPaymentProof"
      | "transferOwnership"
      | "unpause"
      | "usdc"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyVolumeReset"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EscrowCreated"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentProofSubmitted"
      | "StakeDeposited"
      | "StakeSlashed"
      | "StakeWithdrawn"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "SLASH_DISPUTE_LOST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_FAKE_PROOF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_LATE_RELEASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_ORDER_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PAYMENT_REVERSAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseStakeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredStake",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [BytesLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeDAO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAvailableStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastVolumeReset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDailyVolume",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentMethodRisk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rateLimitSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "riskMultipliers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setArbitrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeDAO",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDailyVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "submitPaymentProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "SLASH_DISPUTE_LOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_FAKE_PROOF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_LATE_RELEASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_ORDER_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PAYMENT_REVERSAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbitrator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseStakeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputeDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStakeProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastVolumeReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDailyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentMethodRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateLimitSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDailyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitPaymentProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace DailyVolumeResetEvent {
  export type InputTuple = [oldVolume: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [oldVolume: bigint, timestamp: bigint];
  export interface OutputObject {
    oldVolume: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    raiser: AddressLike,
    reason: string
  ];
  export type OutputTuple = [orderId: string, raiser: string, reason: string];
  export interface OutputObject {
    orderId: string;
    raiser: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, winner: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    stakeAmount: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    sender: string,
    recipient: string,
    amount: bigint,
    stakeAmount: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    orderId: string;
    sender: string;
    recipient: string;
    amount: bigint;
    stakeAmount: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, sender: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProofSubmittedEvent {
  export type InputTuple = [orderId: BytesLike, proofHash: BytesLike];
  export type OutputTuple = [orderId: string, proofHash: string];
  export interface OutputObject {
    orderId: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeSlashedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, amount: bigint, reason: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface P2PEscrowV2 extends BaseContract {
  connect(runner?: ContractRunner | null): P2PEscrowV2;
  waitForDeployment(): Promise<this>;

  interface: P2PEscrowV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SLASH_DISPUTE_LOST: TypedContractMethod<[], [bigint], "view">;

  SLASH_FAKE_PROOF: TypedContractMethod<[], [bigint], "view">;

  SLASH_LATE_RELEASE: TypedContractMethod<[], [bigint], "view">;

  SLASH_ORDER_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  SLASH_PAYMENT_REVERSAL: TypedContractMethod<[], [bigint], "view">;

  arbitrator: TypedContractMethod<[], [string], "view">;

  baseStakeBps: TypedContractMethod<[], [bigint], "view">;

  calculateRequiredStake: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, riskScore: BigNumberish],
    [bigint],
    "view"
  >;

  createEscrow: TypedContractMethod<
    [
      orderId: BytesLike,
      amount: BigNumberish,
      recipient: AddressLike,
      expiresAt: BigNumberish,
      riskScore: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  dailyVolume: TypedContractMethod<[], [bigint], "view">;

  depositStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeDAO: TypedContractMethod<[], [string], "view">;

  disputeTimeout: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        sender: string;
        recipient: string;
        amount: bigint;
        fee: bigint;
        stakeAmount: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        disputedAt: bigint;
        disputeReason: string;
        paymentProofHash: string;
      }
    ],
    "view"
  >;

  getAvailableStake: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEscrow: TypedContractMethod<
    [orderId: BytesLike],
    [P2PEscrowV2.EscrowStructOutput],
    "view"
  >;

  getStakeProfile: TypedContractMethod<
    [user: AddressLike],
    [P2PEscrowV2.StakeProfileStructOutput],
    "view"
  >;

  lastVolumeReset: TypedContractMethod<[], [bigint], "view">;

  maxDailyVolume: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentMethodRisk: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [string],
    "nonpayable"
  >;

  rateLimitSeconds: TypedContractMethod<[], [bigint], "view">;

  refundEscrow: TypedContractMethod<
    [orderId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  releaseEscrow: TypedContractMethod<
    [orderId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [orderId: BytesLike, favorSender: boolean, slashLoser: boolean],
    [void],
    "nonpayable"
  >;

  riskMultipliers: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        low: bigint;
        medium: bigint;
        high: bigint;
        critical: bigint;
      }
    ],
    "view"
  >;

  setArbitrator: TypedContractMethod<
    [_arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setBaseStake: TypedContractMethod<
    [_stakeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDisputeDAO: TypedContractMethod<
    [_disputeDAO: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxDailyVolume: TypedContractMethod<
    [_volume: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        baseStake: bigint;
        lockedStake: bigint;
        tradingLimit: bigint;
        lastTradeTime: bigint;
        completedTrades: bigint;
        disputesLost: bigint;
        isLP: boolean;
      }
    ],
    "view"
  >;

  submitPaymentProof: TypedContractMethod<
    [orderId: BytesLike, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  withdrawStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SLASH_DISPUTE_LOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_FAKE_PROOF"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_LATE_RELEASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_ORDER_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PAYMENT_REVERSAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbitrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseStakeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateRequiredStake"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, riskScore: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      amount: BigNumberish,
      recipient: AddressLike,
      expiresAt: BigNumberish,
      riskScore: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeDAO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        sender: string;
        recipient: string;
        amount: bigint;
        fee: bigint;
        stakeAmount: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        disputedAt: bigint;
        disputeReason: string;
        paymentProofHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAvailableStake"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [P2PEscrowV2.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakeProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [P2PEscrowV2.StakeProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastVolumeReset"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxDailyVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentMethodRisk"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rateLimitSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundEscrow"
  ): TypedContractMethod<[orderId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<[orderId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [orderId: BytesLike, favorSender: boolean, slashLoser: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskMultipliers"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        low: bigint;
        medium: bigint;
        high: bigint;
        critical: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setArbitrator"
  ): TypedContractMethod<[_arbitrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBaseStake"
  ): TypedContractMethod<[_stakeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDisputeDAO"
  ): TypedContractMethod<[_disputeDAO: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxDailyVolume"
  ): TypedContractMethod<[_volume: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        baseStake: bigint;
        lockedStake: bigint;
        tradingLimit: bigint;
        lastTradeTime: bigint;
        completedTrades: bigint;
        disputesLost: bigint;
        isLP: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitPaymentProof"
  ): TypedContractMethod<
    [orderId: BytesLike, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DailyVolumeReset"
  ): TypedContractEvent<
    DailyVolumeResetEvent.InputTuple,
    DailyVolumeResetEvent.OutputTuple,
    DailyVolumeResetEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProofSubmitted"
  ): TypedContractEvent<
    PaymentProofSubmittedEvent.InputTuple,
    PaymentProofSubmittedEvent.OutputTuple,
    PaymentProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StakeSlashed"
  ): TypedContractEvent<
    StakeSlashedEvent.InputTuple,
    StakeSlashedEvent.OutputTuple,
    StakeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DailyVolumeReset(uint256,uint256)": TypedContractEvent<
      DailyVolumeResetEvent.InputTuple,
      DailyVolumeResetEvent.OutputTuple,
      DailyVolumeResetEvent.OutputObject
    >;
    DailyVolumeReset: TypedContractEvent<
      DailyVolumeResetEvent.InputTuple,
      DailyVolumeResetEvent.OutputTuple,
      DailyVolumeResetEvent.OutputObject
    >;

    "DisputeRaised(bytes32,address,string)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,address,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowCreated(bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentProofSubmitted(bytes32,bytes32)": TypedContractEvent<
      PaymentProofSubmittedEvent.InputTuple,
      PaymentProofSubmittedEvent.OutputTuple,
      PaymentProofSubmittedEvent.OutputObject
    >;
    PaymentProofSubmitted: TypedContractEvent<
      PaymentProofSubmittedEvent.InputTuple,
      PaymentProofSubmittedEvent.OutputTuple,
      PaymentProofSubmittedEvent.OutputObject
    >;

    "StakeDeposited(address,uint256)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "StakeSlashed(address,uint256,string)": TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;
    StakeSlashed: TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
