/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TrustScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeContract"
      | "authorizedContracts"
      | "getReputation"
      | "getTrustScore"
      | "owner"
      | "recordDispute"
      | "recordTrade"
      | "renounceOwnership"
      | "reputations"
      | "transferOwnership"
      | "updateLPStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractAuthorized"
      | "DisputeRecorded"
      | "LPStatusUpdated"
      | "OwnershipTransferred"
      | "TradeCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeContract",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedContracts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDispute",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTrade",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLPStatus",
    values: [AddressLike, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLPStatus",
    data: BytesLike
  ): Result;
}

export namespace ContractAuthorizedEvent {
  export type InputTuple = [contractAddr: AddressLike, status: boolean];
  export type OutputTuple = [contractAddr: string, status: boolean];
  export interface OutputObject {
    contractAddr: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRecordedEvent {
  export type InputTuple = [user: AddressLike, lost: boolean];
  export type OutputTuple = [user: string, lost: boolean];
  export interface OutputObject {
    user: string;
    lost: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPStatusUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    isLP: boolean,
    stake: BigNumberish
  ];
  export type OutputTuple = [user: string, isLP: boolean, stake: bigint];
  export interface OutputObject {
    user: string;
    isLP: boolean;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCompletedEvent {
  export type InputTuple = [
    user: AddressLike,
    volume: BigNumberish,
    asSeller: boolean
  ];
  export type OutputTuple = [user: string, volume: bigint, asSeller: boolean];
  export interface OutputObject {
    user: string;
    volume: bigint;
    asSeller: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustScore extends BaseContract {
  connect(runner?: ContractRunner | null): TrustScore;
  waitForDeployment(): Promise<this>;

  interface: TrustScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeContract: TypedContractMethod<
    [contractAddr: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  authorizedContracts: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getReputation: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        completedTrades: bigint;
        totalVolume: bigint;
        successfulReleases: bigint;
        disputes: bigint;
        disputesLost: bigint;
        isLP: boolean;
      }
    ],
    "view"
  >;

  getTrustScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDispute: TypedContractMethod<
    [user: AddressLike, lost: boolean],
    [void],
    "nonpayable"
  >;

  recordTrade: TypedContractMethod<
    [user: AddressLike, volume: BigNumberish, asSeller: boolean],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        completedTrades: bigint;
        totalVolume: bigint;
        successfulReleases: bigint;
        disputes: bigint;
        disputesLost: bigint;
        firstTradeAt: bigint;
        lastTradeAt: bigint;
        isLP: boolean;
        lpStake: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLPStatus: TypedContractMethod<
    [user: AddressLike, isLP: boolean, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeContract"
  ): TypedContractMethod<
    [contractAddr: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedContracts"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        completedTrades: bigint;
        totalVolume: bigint;
        successfulReleases: bigint;
        disputes: bigint;
        disputesLost: bigint;
        isLP: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDispute"
  ): TypedContractMethod<
    [user: AddressLike, lost: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTrade"
  ): TypedContractMethod<
    [user: AddressLike, volume: BigNumberish, asSeller: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        completedTrades: bigint;
        totalVolume: bigint;
        successfulReleases: bigint;
        disputes: bigint;
        disputesLost: bigint;
        firstTradeAt: bigint;
        lastTradeAt: bigint;
        isLP: boolean;
        lpStake: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLPStatus"
  ): TypedContractMethod<
    [user: AddressLike, isLP: boolean, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractAuthorized"
  ): TypedContractEvent<
    ContractAuthorizedEvent.InputTuple,
    ContractAuthorizedEvent.OutputTuple,
    ContractAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRecorded"
  ): TypedContractEvent<
    DisputeRecordedEvent.InputTuple,
    DisputeRecordedEvent.OutputTuple,
    DisputeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "LPStatusUpdated"
  ): TypedContractEvent<
    LPStatusUpdatedEvent.InputTuple,
    LPStatusUpdatedEvent.OutputTuple,
    LPStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TradeCompleted"
  ): TypedContractEvent<
    TradeCompletedEvent.InputTuple,
    TradeCompletedEvent.OutputTuple,
    TradeCompletedEvent.OutputObject
  >;

  filters: {
    "ContractAuthorized(address,bool)": TypedContractEvent<
      ContractAuthorizedEvent.InputTuple,
      ContractAuthorizedEvent.OutputTuple,
      ContractAuthorizedEvent.OutputObject
    >;
    ContractAuthorized: TypedContractEvent<
      ContractAuthorizedEvent.InputTuple,
      ContractAuthorizedEvent.OutputTuple,
      ContractAuthorizedEvent.OutputObject
    >;

    "DisputeRecorded(address,bool)": TypedContractEvent<
      DisputeRecordedEvent.InputTuple,
      DisputeRecordedEvent.OutputTuple,
      DisputeRecordedEvent.OutputObject
    >;
    DisputeRecorded: TypedContractEvent<
      DisputeRecordedEvent.InputTuple,
      DisputeRecordedEvent.OutputTuple,
      DisputeRecordedEvent.OutputObject
    >;

    "LPStatusUpdated(address,bool,uint256)": TypedContractEvent<
      LPStatusUpdatedEvent.InputTuple,
      LPStatusUpdatedEvent.OutputTuple,
      LPStatusUpdatedEvent.OutputObject
    >;
    LPStatusUpdated: TypedContractEvent<
      LPStatusUpdatedEvent.InputTuple,
      LPStatusUpdatedEvent.OutputTuple,
      LPStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TradeCompleted(address,uint256,bool)": TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;
    TradeCompleted: TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;
  };
}
