/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "DisputeDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DisputeDAO__factory>;
    getContractFactory(
      name: "P2PEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P2PEscrow__factory>;
    getContractFactory(
      name: "P2PEscrowV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P2PEscrowV2__factory>;
    getContractFactory(
      name: "P2PEscrowV3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P2PEscrowV3__factory>;
    getContractFactory(
      name: "P2PEscrowV4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P2PEscrowV4__factory>;
    getContractFactory(
      name: "P2PEscrowV5",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P2PEscrowV5__factory>;
    getContractFactory(
      name: "TrustScore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustScore__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "DisputeDAO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DisputeDAO>;
    getContractAt(
      name: "P2PEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P2PEscrow>;
    getContractAt(
      name: "P2PEscrowV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P2PEscrowV2>;
    getContractAt(
      name: "P2PEscrowV3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P2PEscrowV3>;
    getContractAt(
      name: "P2PEscrowV4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P2PEscrowV4>;
    getContractAt(
      name: "P2PEscrowV5",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P2PEscrowV5>;
    getContractAt(
      name: "TrustScore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustScore>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "DisputeDAO",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeDAO>;
    deployContract(
      name: "P2PEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrow>;
    deployContract(
      name: "P2PEscrowV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV2>;
    deployContract(
      name: "P2PEscrowV3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV3>;
    deployContract(
      name: "P2PEscrowV4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV4>;
    deployContract(
      name: "P2PEscrowV5",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV5>;
    deployContract(
      name: "TrustScore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustScore>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "DisputeDAO",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeDAO>;
    deployContract(
      name: "P2PEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrow>;
    deployContract(
      name: "P2PEscrowV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV2>;
    deployContract(
      name: "P2PEscrowV3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV3>;
    deployContract(
      name: "P2PEscrowV4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV4>;
    deployContract(
      name: "P2PEscrowV5",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P2PEscrowV5>;
    deployContract(
      name: "TrustScore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustScore>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
